# Generated by Django 3.1.4 on 2021-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(related_name='transactions', to='money.Tag'),
        ),
    ]
