# Generated by Django 3.1.4 on 2021-01-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20210129_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='upwork', max_length=200),
            preserve_default=False,
        ),
    ]
