# Generated by Django 3.1.4 on 2021-01-29 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_utc', models.DateTimeField(auto_now_add=True)),
                ('updated_utc', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_utc', models.DateTimeField(auto_now_add=True)),
                ('updated_utc', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('note', models.ManyToManyField(related_name='tags', to='note.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
