# Generated by Django 3.1.4 on 2021-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20210129_1516'),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes', to='money.Tag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
